import React from 'react';
import { ReportTable, SideLengthsList } from './ResultsDisplay';

export const PrintLayout = React.forwardRef(({ results, reportImage, imageName }, ref) => {
  if (!results || !reportImage) return null;
  const generatedAt = new Date().toLocaleString('bn-BD', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    hour12: true
  });
  return (
    <div ref={ref} className="hidden print:block font-sans">
      <div className="flex items-center justify-between mb-2">
        <div className="text-sm text-muted-foreground">{generatedAt}</div>
        <div className="text-sm font-medium text-foreground">Made By: Golap Hasan</div>
      </div>
      <h1 className="text-2xl font-bold mb-1 text-center">মৌজা ম্যাপ হিসাব রিপোর্ট</h1>
      <div className="text-xs text-muted-foreground border-b border-border pb-2 mb-6 text-center">
        {imageName ? (<span>সোর্স: {imageName}</span>) : (<span>সোর্স: আপলোড করা ম্যাপ</span>)}
      </div>
      <div className="mb-8 break-inside-avoid">
        <h2 className="text-xl font-semibold mb-2 border-b pb-1">গণনা করা ক্ষেত্রফল</h2>
        <ReportTable results={results} />
      </div>
      <div className="mb-8 break-inside-avoid">
        {/* <h2 className="text-xl font-semibold mb-2 border-b pb-1">পরিসীমা:</h2> */}
        <SideLengthsList lengths={results.lengths} />
      </div>
      <div className="break-inside-avoid">
        <h2 className="text-xl font-semibold mb-2 border-b pb-1">প্লট সহ ম্যাপ</h2>
        <img src={reportImage} alt="গণনা করা প্লট" className="w-full md:h-125 border rounded-md" />
      </div>
      <div className="mt-8 pt-4 border-t text-center text-sm text-muted-foreground">
        <p>This Report Generated by Mouza Map Calculator</p>
        <p className="mt-1">contact: golaphasan379@gmail.com</p>
      </div>
    </div>
  );
});

PrintLayout.displayName = 'PrintLayout';
